Update scorchdb

diff --git a/scorchdb b/scorchdb
--- a/scorchdb
+++ b/scorchdb
@@ -43,7 +43,7 @@
 # User configurable
 # =================
 typeset local     file_DB=txtdb			# The default DB file name
-typeset local dir_Project=~/scorch/ScORCH/projects
+typeset local dir_Project=~/scorch/projects
 typeset              c_FS=" "			# The field seperator character
 
 
@@ -52,7 +52,7 @@ typeset              c_FS=" "			# The field seperator character
 typeset -a arr_Columns=""
 typeset    str_Options=""
 typeset    str_Columns=""
-typeset       str_From=
+typeset       str_From=""
 typeset      str_Regex=""
 typeset         b_List=""
 typeset       b_Strict=""
@@ -73,6 +73,7 @@ OPTIONS
 \t--list         \tList all available column names found in default
 \t               \tfile or file specified\n
 \t--strict       \tOnly allow whitespace between multiple strings\n
+\t-def \"<string>\" \tDefinition of columns (useful for non-writable file(
 \t-<col> [-<col>]\tDisplay result for columns specified\n
 \t<regex string> \tA regex expression used to return columns\n
 \t+<col> <string>\tLimit to next search string to the column mentioned (horizonal grep)
@@ -84,7 +85,7 @@ EXAMPLES
 \tscorchdb --file testdb\n
 \tWill list the available column searches in the testdb file\n\n
 \tscorchdb +os windows\n
-\tDisplay all columns where the os column contains the word windows\n"
+\tDisplay all columns where the os column contains the word windows"
 exit 0
 }
 # pcmdb host -lai
@@ -102,6 +103,7 @@ if [ $# -ne 0 ] ; then
       -l  | --list ) b_List=1 ;;
       -f  | --file ) shift ; file_DB="$1"  ;;
       -fs | --FS   ) shift ; c_FS="$1" ;;
+	  -def         ) shift ; str_Columns="$1" ;;
       --strict     ) b_Strict=1 ;;
       -*           ) str_Options="${str_Options} $1"            ;;
       +*           ) str_From="${str_From} $1:$2" ; shift ;;
@@ -113,128 +115,149 @@ fi
 
 # Check is DB file is readable
 # ============================
-if [[ ! -f ${file_DB} ]] ; then
-#echo "Cannot find ${file_DB} - $(ls ${file_DB})switching to project mode"
-  file_DB="$(find ${dir_Project} -name ${file_DB})"
+[ ! -f ${file_DB} ] || [ ! -r ${file_DB} ] && echo "${file_DB}: not a readable file" && exit 1
+
+
+# Find the defined columns names in the text file and turn it into an array
+# =========================================================================
+[ "${str_Columns}" = "" ] && typeset local str_Columns=$(grep "^#DEF" ${file_DB} 2>/dev/null | head -1)
+typeset local c_tmpFS=$(grep "^#FS" ${file_DB} 2>/dev/null | head -1)
+[ ! -z "${c_tmpFS}" ]     && str_FS="-F${c_tmpFS#\#FS=}"
+[   -z "${str_Columns}" ] && echo "Cannot find a column definition in file:${file_DB}" && exit 1
+arr_Columns=(${str_Columns#\#DEF})
+
+
+# If --list is present, show the columns defined
+# ==============================================
+[ ! -z "${b_List}" ] && echo " ${arr_Columns[@]}" | sed 's/ / -/g' && exit 0
+
+
+# If a Regex is passed set the cmd for grep
+# =========================================
+[ ! -z "${str_Regex}" ] && cmd_GREP="| grep -i "  || cmd_GREP=""
+
+
+# If we dont find any diplsay usage
+# =================================
+# Usage
+
+
+# We can now get rid of the minus signs in the passed column requests
+# ===================================================================
+str_Options=$(echo ${str_Options} | tr -d "-")
+typeset -a arr_Options=(${str_Options})
+
+
+# Check if Variable in Columns list
+# =================================
+typeset -i int_ColumnCount=1
+typeset -i int_OptionCount=1
+for str_Option in ${arr_Options[@]} ; do
+  [ ${int_OptionCount} -lt ${#arr_Options[@]} ] && c_Comma="," || c_Comma=""
+  # Check if a comman will be required at the end
+  int_ColumnCount=1
+  b_Found=0
+  for str_Column in ${arr_Columns[@]}; do
+    if [ "${str_Option}" = "${str_Column}" ] ; then
+	   str_AWK="${str_AWK} \$${int_ColumnCount}${c_Comma}"
+	   b_Found=1
+    fi
+    (( int_ColumnCount++ ))
+  done
+  (( b_Found == 0 )) && printf "Cannot find column ${str_Option}. Available columns:\n" &&  echo " ${arr_Columns[@]}" | sed 's/ / -/g' && exit 1
+  (( int_OptionCount++ ))
+done
+
+(( b_Strict == 1 )) && str_Regex=$(echo "${str_Regex}" | sed "s/[\t| ]\+/ /g") ||  str_Regex=$(echo "${str_Regex}" | sed "s/ /\\.\*/g")
+(( b_Strict == 1 )) && c_GrepCase=""
+
+[ -z "${str_Regex}" ] && str_Regex= || str_Regex="\"${str_Regex}\""
+
+# Run the command to get the right values
+# =======================================
+if [ -z "${str_From}" ] ; then
+  if (( b_Strict == 1 )) ; then
+	# Need to manage ONE or more whitespace. Actually it would be better to match two or more spaces.
+	eval "sed \"s/[\t|  ]\+/ /g\" ${file_DB} ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+  else
+    eval "cat ${file_DB} ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+  fi
+  exit
 fi
 
-#elif [ ! -r ${file_DB} ] ; then
-#  echo "${file_DB}: not a readable file"
-#  exit 1
-#fi
-
-fn_GetDetail()
-{
-
-  # Each file
-  typeset local file_DB=${1}
-  # Find the defined columns names in the text file and turn it into an array
-  # =========================================================================
-  typeset local str_Columns=$(grep "^#DEF" ${file_DB} 2>/dev/null | head -1)
-  typeset local c_tmpFS=$(grep "^#FS" ${file_DB} 2>/dev/null | head -1)
-  [ ! -z "${c_tmpFS}" ]     && str_FS="-F${c_tmpFS#\#FS=}"
-  [   -z "${str_Columns}" ] && echo "Cannot find a column definition in file:${file_DB}" && exit 1
-  arr_Columns=(${str_Columns#\#DEF})
-
-
-  # If --list is present, show the columns defined
-  # ==============================================
-  [ ! -z "${b_List}" ] && echo " ${arr_Columns[@]}" | sed 's/ / -/g' && return 0
-
-
-  # If a Regex is passed set the cmd for grep
-  # =========================================
-  [ ! -z "${str_Regex}" ] && cmd_GREP="| grep -i "  || cmd_GREP=""
-
-
-  # If we dont find any diplsay usage
-  # =================================
-  # Usage
-
-
-  # We can now get rid of the minus signs in the passed column requests
-  # ===================================================================
-  str_Options=$(echo ${str_Options} | tr -d "-")
-  typeset -a arr_Options=(${str_Options})
-
-
-  # Check if Variable in Columns list
-  # =================================
-  typeset -i int_ColumnCount=1
-  typeset -i int_OptionCount=1
-  for str_Option in ${arr_Options[@]} ; do
-    [ ${int_OptionCount} -lt ${#arr_Options[@]} ] && c_Comma="," || c_Comma=""
-    # Check if a comman will be required at the end
-    int_ColumnCount=1
-    b_Found=0
-    for str_Column in ${arr_Columns[@]}; do
-      if [ "${str_Option}" = "${str_Column}" ] ; then
-        str_AWK="${str_AWK} \$${int_ColumnCount}${c_Comma}"
-        b_Found=1
-      fi
-      (( int_ColumnCount++ ))
-    done
-    (( b_Found == 0 )) && printf "Cannot find column ${str_Option}. Available columns:\n" &&  echo " ${arr_Columns[@]}" | sed 's/ / -/g' && exit 1
-    (( int_OptionCount++ ))
-  done
-
-  (( b_Strict == 1 )) && str_Regex=$(echo "${str_Regex}" | sed "s/[\t| ]\+/ /g") ||  str_Regex=$(echo "${str_Regex}" | sed "s/ /\\.\*/g")
-  (( b_Strict == 1 )) && c_GrepCase=""
-
-  [ -z "${str_Regex}" ] && str_Regex= || str_Regex="\"${str_Regex}\""
-
-  # Run the command to get the right values
-  # =======================================
-  if [ -z "${str_From}" ] ; then
-    if (( b_Strict == 1 )) ; then
-      # Need to manage ONE or more whitespace. Actually it would be better to match two or more spaces.
-      eval "sed \"s/[\t|  ]\+/ /g\" ${file_DB} ${cmd_GREP} ${str_Regex} | egrep -v \"^#|^ *$\" | awk ${str_FS} '{print ${str_AWK}}'"
-    else
-      eval "cat ${file_DB} ${cmd_GREP} ${str_Regex} | egrep -v \"^#|^ *$\" | awk ${str_FS} '{print ${str_AWK}}'"
+# FROM method chosen - a little bit slower but restricts the search to the column specified
+# =========================================================================================
+str_Like=""
+b_FoundColumn="FALSE"
+typeset -i int_ColumnCount=1
+typeset -i int_OptionCount=1
+for str_Option in ${str_From} ; do
+  str_Column=${str_Option#+*:}
+  str_Value=${str_Option%*:*}
+  [ ${int_OptionCount} -lt ${#arr_Options[@]} ] && c_Comma="," || c_Comma=""
+  # Check if a comma will be required at the end
+  int_ColumnCount=1
+  for str_Check in ${arr_Columns[@]}; do
+    if [ "+${str_Check}" = "${str_Value}" ] ; then
+       b_FoundColumn=TRUE
+	   int_MyCount=${int_ColumnCount}
+	   str_MyStr=${str_Column}
+	   [ -z "${str_Like}" ] && str_Like="${str_Value} = ${str_Column}" ||  str_Like="${str_Like} AND ${str_Value} = ${str_Column}"
+	   break
     fi
+    (( int_ColumnCount++ ))
+  done
+  (( int_OptionCount++ ))
+  if [ "${b_FoundColumn}" = "FALSE" ] ; then
+    echo "ERROR - no column found"
+    exit 1
   fi
-
-
-  if [ ! -z ${str_From} ] ; then 
-    # FROM method chosen - a little bit slower but restricts the search to the column specified
-    # =========================================================================================
-    str_Like=""
-    b_FoundColumn="FALSE"
-    typeset -i int_ColumnCount=1
-    typeset -i int_OptionCount=1
-    for str_Option in ${str_From} ; do
-      str_Column=${str_Option#+*:}
-      str_Value=${str_Option%*:*}
-      [ ${int_OptionCount} -lt ${#arr_Options[@]} ] && c_Comma="," || c_Comma=""
-      # Check if a comma will be required at the end
-      int_ColumnCount=1
-      for str_Check in ${arr_Columns[@]}; do
-        if [ "+${str_Check}" = "${str_Value}" ] ; then
-          b_FoundColumn=TRUE
-          int_MyCount=${int_ColumnCount}
-          str_MyStr=${str_Column}
-          [ -z "${str_Like}" ] && str_Like="${str_Value} = ${str_Column}" ||  str_Like="${str_Like} AND ${str_Value} = ${str_Column}"
-          break
-        fi
-        (( int_ColumnCount++ ))
-      done
-      (( int_OptionCount++ ))
-      if [ "${b_FoundColumn}" = "FALSE" ] ; then
-        echo "ERROR - no column found"
-        exit 1
-      fi
-    done
-
-
-    arr_Found=$(eval "awk ${str_FS} '{print \$$int_ColumnCount}' ${file_DB} | grep ${c_GrepCase} -n ${str_MyStr} | cut -d: -f1")
-    for int_EachGrep in ${arr_Found} ; do
-      eval "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | egrep -v \"^#|^ *$\" | awk ${str_FS} '{print ${str_AWK}}'"
-    done
-  fi
-}
-
-for str_EachFile in ${file_DB} ; do
-  str_AWK=""
-  fn_GetDetail ${str_EachFile}
 done
+
+arr_Found=$(eval "awk ${str_FS} '{print \$$int_ColumnCount}' ${file_DB} | grep ${c_GrepCase} -n ${str_MyStr} | cut -d: -f1")
+for int_EachGrep in ${arr_Found} ; do
+  eval "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+done
+
 exit
+
+#echo select ${str_Options} from ${file_DB} where ${str_Like}
+#echo "for int_EachGrep in \$(eval awk '{print \$$int_ColumnCount}' ${file_DB} | grep -n ${str_MyStr} | cut -d: -f1) ; do"
+# Work for selecting from specific columns
+#echo ""
+#echo "The checks"
+#echo "Options       :${arr_Options[@]}"
+#echo "From column checks :${str_From}"
+#echo "regex         :${str_Regex}"
+#echo ${arr_Columns[@]##*os} ; echo $?
+#echo ${arr_Columns[@]#test} ; echo $?
+#str_FS="-F${c_tmpFS#\#FS=}"
+#str_AWK=""
+
+#echo ${int_OptionCount},${int_ColumnCount}
+#echo "Need to check Columns ${str_AWK}"
+
+#printf "\nTesting mode:\n"
+#arr_Found=$(eval "awk  '{print \$$int_ColumnCount}' ${file_DB} | grep ${c_GrepCase} -n ${str_MyStr} | cut -d: -f1")
+#echo "awk '{print \$$int_ColumnCount}' ${file_DB} | grep -in ${str_MyStr} | cut -d: -f1"
+
+#for int_EachGrep in ${arr_Found} ; do
+#  echo "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+#  eval "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+#done
+
+#printf "\n\nPartially works:\n"
+#for int_EachGrep in $(awk '{print $int_ColumnCount}' ${file_DB} | grep -n ${str_MyStr} | cut -d: -f1) ; do
+#  echo "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+#  eval "head -${int_EachGrep} ${file_DB} | tail -1 ${cmd_GREP} ${str_Regex} | grep -v \"^#\" | awk ${str_FS} '{print ${str_AWK}}'"
+#done
+
+#printf "\nPart2:\n\t./scorchdb  +os Windows\n"
+ # echo Check for ${str_Column} in $str_Value column
+ # echo "Version with 10 and FS <${c_FS}>"
+#  grep "${c_FS}*.*${c_FS}*.*${c_FS}*10" ${file_DB}
+#  echo "checking str_Option ${str_Option} in ${str_Column} value ${str_Value} "
+#	   echo "str_Option ${str_Option} found in column ${int_ColumnCount}"
+	   #str_AWK="${str_AWK} \$${int_ColumnCount}${c_Comma} : ${str_Check} "
+#echo "Need this to work when FS != \" \" "
+#echo select ${str_Options} from ${file_DB} where ${str_Like}
